// Generated by CoffeeScript 2.3.2
var m = require('mithril')
var SiteMeta = require('./site-meta')

module.exports = {
  view: function(vnode) {
    var attrs;
    attrs = vnode.attrs;
    return [
      m("!doctype[html]"),
      m(
        "html", [
          m("head", [
            m(SiteMeta, attrs),
            m("title", attrs.title),
            m("link", {
              rel: "stylesheet",
              href: attrs.fingerprint[`${attrs.css}/app.css`],
              type: "text/css"
            })
          ]),
          m("body", [
            m("#container.content", attrs.content),
            m("script[async]", {
              src: attrs.fingerprint[`${attrs.js}/app.js`]
            })
          ])
        ]
      )
    ];
  }
};
