// Generated by CoffeeScript 2.3.2
var m = require('mithril')
var SiteMeta = require('./site-meta')

module.exports = {
  view: function(vnode) {
    return m(
      "svg",
      {
        viewBox: "0 0 32 29.6"
      },
      m("path", {
        d:
          "M23.6 0c-3.4 0-6.3 2.7-7.6 5.6-1.3-3-4.2-5.6-7.6-5.6C3.8 0 0 3.8 0 8.4c0 9.4 9.5 12 16 21.2 6-9.3 16-12 16-21.2C32 3.8 28.2 0 23.6 0z",
        fill: "currentColor"
      })
    );
  }
};
