// Generated by CoffeeScript 2.3.2
import m from "mithril";

import Base from "./_components/base";

import Heart from "./_components/heart";

export default {
  ctrl: function(file, metalsmith) {
    this.attrs = metalsmith._metadata;
    this.attrs.title = file.title;
    this.attrs.content = [
      m(".logos", [
        m(
          ".logo",
          m("img", {
            src: `${attrs.paths.img}/metalsmith-logo.svg`,
            alt: "Metalsmith"
          })
        ),
        m(".heart", m(Heart)),
        m(
          ".logo",
          m("img", {
            src: `${attrs.paths.img}/webpack-logo.svg`,
            alt: "Webpack"
          })
        )
      ]),
      m(".content", m.trust(file.html))
    ];
    return this;
  },
  view: function(ctrl, file, metalsmith) {
    return m("p", "hi");
    // return m(Base, ctrl.attrs);
  }
};
